//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace WCFServiceWebRole1
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SadAss2SQLEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SadAss2SQLEntities object using the connection string found in the 'SadAss2SQLEntities' section of the application configuration file.
        /// </summary>
        public SadAss2SQLEntities() : base("name=SadAss2SQLEntities", "SadAss2SQLEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SadAss2SQLEntities object.
        /// </summary>
        public SadAss2SQLEntities(string connectionString) : base(connectionString, "SadAss2SQLEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SadAss2SQLEntities object.
        /// </summary>
        public SadAss2SQLEntities(EntityConnection connection) : base(connection, "SadAss2SQLEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ProjAppTable> ProjAppTables
        {
            get
            {
                if ((_ProjAppTables == null))
                {
                    _ProjAppTables = base.CreateObjectSet<ProjAppTable>("ProjAppTables");
                }
                return _ProjAppTables;
            }
        }
        private ObjectSet<ProjAppTable> _ProjAppTables;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ProjAppTables EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProjAppTables(ProjAppTable projAppTable)
        {
            base.AddObject("ProjAppTables", projAppTable);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SadAss2SQLModel", Name="ProjAppTable")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ProjAppTable : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ProjAppTable object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="latitude">Initial value of the Latitude property.</param>
        /// <param name="longitude">Initial value of the Longitude property.</param>
        /// <param name="tag1">Initial value of the Tag1 property.</param>
        /// <param name="tag2">Initial value of the Tag2 property.</param>
        public static ProjAppTable CreateProjAppTable(global::System.Int32 id, global::System.String name, global::System.String latitude, global::System.String longitude, global::System.String tag1, global::System.String tag2)
        {
            ProjAppTable projAppTable = new ProjAppTable();
            projAppTable.ID = id;
            projAppTable.Name = name;
            projAppTable.Latitude = latitude;
            projAppTable.Longitude = longitude;
            projAppTable.Tag1 = tag1;
            projAppTable.Tag2 = tag2;
            return projAppTable;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Latitude
        {
            get
            {
                return _Latitude;
            }
            set
            {
                OnLatitudeChanging(value);
                ReportPropertyChanging("Latitude");
                _Latitude = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Latitude");
                OnLatitudeChanged();
            }
        }
        private global::System.String _Latitude;
        partial void OnLatitudeChanging(global::System.String value);
        partial void OnLatitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Longitude
        {
            get
            {
                return _Longitude;
            }
            set
            {
                OnLongitudeChanging(value);
                ReportPropertyChanging("Longitude");
                _Longitude = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Longitude");
                OnLongitudeChanged();
            }
        }
        private global::System.String _Longitude;
        partial void OnLongitudeChanging(global::System.String value);
        partial void OnLongitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Tag1
        {
            get
            {
                return _Tag1;
            }
            set
            {
                OnTag1Changing(value);
                ReportPropertyChanging("Tag1");
                _Tag1 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Tag1");
                OnTag1Changed();
            }
        }
        private global::System.String _Tag1;
        partial void OnTag1Changing(global::System.String value);
        partial void OnTag1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Tag2
        {
            get
            {
                return _Tag2;
            }
            set
            {
                OnTag2Changing(value);
                ReportPropertyChanging("Tag2");
                _Tag2 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Tag2");
                OnTag2Changed();
            }
        }
        private global::System.String _Tag2;
        partial void OnTag2Changing(global::System.String value);
        partial void OnTag2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tag3
        {
            get
            {
                return _Tag3;
            }
            set
            {
                OnTag3Changing(value);
                ReportPropertyChanging("Tag3");
                _Tag3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Tag3");
                OnTag3Changed();
            }
        }
        private global::System.String _Tag3;
        partial void OnTag3Changing(global::System.String value);
        partial void OnTag3Changed();

        #endregion

    
    }

    #endregion

    
}
